name: Run playbook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install ansible

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          directory: ./
          configuration: |
            [defaults]
            callbacks_enabled = ansible.posix.profile_tasks, ansible.posix.timer
            stdout_callback = yaml
            nocows = false
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [all]
            192.168.1.12

            [group1]
            192.168.1.12
          vault_password: ${{ secrets.VAULT_PASSWORD }}
          requirements: galaxy-requirements.yml
          options: |
            --inventory .hosts
            --limit group1
            --extra-vars hello=there
            --verbose
